### ISSUE TITLE
File a bug where Flight can't be added despite following the instruction from User Guide

### ISSUE THREAD

**Issue by wilsonngja** [AY2223S1-CS2113-T17-1/tp#58]
![image](https://user-images.githubusercontent.com/31720838/198551808-a4e93138-4822-4b0c-8ab2-77519c2c8e14.png)
![image](https://user-images.githubusercontent.com/31720838/198551753-e5bfb816-9a7e-4802-944a-284187ced265.png)

When testing, the flight can't be added despite copying the text directly over.

**Comment by ivanthengwr** [comment]
Issue Resolved in latest commit
