### ISSUE TITLE
Unable to test flight add and passenger add features using the user input

### ISSUE THREAD

**Issue by junhaoliu2468** [AY2223S1-CS2113-T17-1/tp#59]
![86fa62c8-6115-4e30-92ab-0b079cfbf923](https://user-images.githubusercontent.com/75772830/198551938-9af82dca-9964-4739-980a-0356c8b01aee.jpg)
![60df7120-41bf-47ac-93ca-a8e95386536c](https://user-images.githubusercontent.com/75772830/198551965-eca6aa9a-c757-4e13-83e9-a395003b442a.jpg)

**Comment by ivanthengwr** [comment]
Resolve the issue in the latest commit
