### ISSUE TITLE
[PE-D][Tester A] Incorrect departure time when adding passenger

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2113-T17-1/tp#63]
App allows passenger to be added to the correct flight with incorrect departure time

Flight KE644 with departure time 2145 does not exist in flight list but passenger can be added

![image.png](https://raw.githubusercontent.com/alfred-leong/ped/main/files/a38ce259-ba24-4251-a30d-9c6ac9aa4724.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: alfred-leong/ped#2

**Comment by ivanthengwr** [comment]
Duplicated issue, issue has already been made prior that will be resolved
