### ISSUE TITLE
[PE-D][Tester A] Departure and boarding times with no checks

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2113-T17-1/tp#64]
App allows boarding time to be after departure time when adding passengers, which does not make sense

![image.png](https://raw.githubusercontent.com/alfred-leong/ped/main/files/6fc10386-0d96-4b14-9afd-bb3da268d772.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: alfred-leong/ped#3

**Comment by ivanthengwr** [comment]
Good catch!

**Comment by ivanthengwr** [comment]
Resolved
