### ISSUE TITLE
[PE-D][Tester A] Invalid time format

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2113-T17-1/tp#71]
Invalid time format of 500, but allowed to be added to passenger list

![image.png](https://raw.githubusercontent.com/alfred-leong/ped/main/files/0a40fb1d-99bf-45d2-a5cc-403695ecbefe.png)

![image.png](https://raw.githubusercontent.com/alfred-leong/ped/main/files/64edc39a-a04b-44d0-b029-d499bab68f04.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: alfred-leong/ped#10

**Comment by ivanthengwr** [comment]
Good catch!

**Comment by ivanthengwr** [comment]
Resolve issue when Rachel's pr is merge
