### ISSUE TITLE
[PE-D][Tester A] Incorrect departure time when deleting

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2113-T17-1/tp#72]
App allows passenger to be deleted from correct flight number but incorrect departure time

![image.png](https://raw.githubusercontent.com/alfred-leong/ped/main/files/b517dd96-4968-4ade-8102-c5e156d67b93.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: alfred-leong/ped#11

**Comment by ivanthengwr** [comment]
Omit input for dt/ in passenger delete operation
