### ISSUE TITLE
[PE-D][Tester A] Deleting passenger not working as intended

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2113-T17-1/tp#74]
Able to delete passenger without typing full name

![image.png](https://raw.githubusercontent.com/alfred-leong/ped/main/files/fe95922c-8574-4939-b0b1-ff838c735db2.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: alfred-leong/ped#13

**Comment by ivanthengwr** [comment]
pr #61 fixes this issue
